// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/longhoang0304/authena-phnx/internal/apps/authena"
)

// Injectors from wire.go:

func InitAuthenaApp() (*authena.AuthenaApp, error) {
	v := authena.NewRoutes()
	handler, err := authena.NewRouter(v)
	if err != nil {
		return nil, err
	}
	httpServer, err := authena.NewHttpServer(handler)
	if err != nil {
		return nil, err
	}
	authenaApp := authena.NewAuthenaApp(httpServer)
	return authenaApp, nil
}
